---

- name: update packages
  dnf:
    name: '*'
    state: latest
    
- name: enable codeready-builder-for-rhel-9-x86_64-rpms repository
  command: "/usr/bin/subscription-manager repos --enable=codeready-builder-for-rhel-9-x86_64-rpms"
  when: ansible_distribution == 'RedHat' and ansible_distribution_release == 'Plow'

- name: import epel key
  rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9

- name: enable epel repository
  dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
    state: present

- name: install software
  dnf:
    name: "{{ rpms }}"
    state: present

- name: disable epel-modular repository
  command: '/usr/bin/dnf config-manager --disable epel-modular'
  when: ansible_distribution == 'RedHat' and ansible_distribution_version == '8.5'
