---

- name: demo directory creation
  file:
    path: "/home/{{ user }}/{{ demo_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    setype: user_home_t
    mode: '0755'

- name: copy demo files
  copy:
    src: "{{ item }}"
    dest: "/home/{{ user }}/{{ demo_dir }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    setype: user_home_t
    mode: '0755'
  with_items:
    - "index.html"
    - "index2.html"
    - "Tux.svg.png"

- name: remove welcome site from httpd
  file:
    path: /etc/httpd/conf.d/welcome.conf
    state: absent

- name: create ostree export directory for httpd
  file:
    path: '/var/www/html/ostree'
    state: directory
    owner: root
    group: root
    setype: httpd_sys_content_t
    mode: '0755'

- name: copy ostree httpd configuration
  copy:
    src: ostree.conf
    dest: /etc/httpd/conf.d/ostree.conf
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'

- name: configure httpd service
  systemd:
    name: httpd
    state: started
    enabled: yes
    masked: no