---

- include_tasks: 01-software.yaml
- include_tasks: 02-services.yaml
- include_tasks: 03-users.yaml
- include_tasks: 04-demo.yaml
#- include_tasks: 05-registry.yaml
#- include_tasks: 06-containers.yaml
- include_tasks: 99-firewalld.yaml
