---

- name: tmp directory creation
  file:
    path: "{{ tmp_dir }}"
    state: directory
    owner: root
    group: root
    setype: tmp_t
    mode: '0755'
  become: yes

- name: kickstart
  template:
    src: edge.ks.j2
    dest: "{{ tmp_dir }}/edge.ks"
    owner: root
    group: root
    setype: tmp_t
    mode: 0640
  become: true

- name: rheledge 8 deployment iso creation
  command: "/usr/sbin/mkksiso -c 'inst.text' {{ tmp_dir }}/edge.ks {{ rhel8_iso }} {{ boot_iso }}"
  become: true
  when: ansible_distribution == 'RedHat' and ansible_distribution_version == '8.5'

- name: rheledge 9 deployment iso creation
  command: "/usr/sbin/mkksiso -c 'inst.text' {{ tmp_dir }}/edge.ks {{ rhel9_iso }} {{ boot_iso }}"
  become: true
  when: ansible_distribution == 'RedHat' and ansible_distribution_release == 'Plow'
